# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J.A.R.V.I.S.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap("background.png"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.Bg_rt = QtWidgets.QLabel(self.centralwidget)
        self.Bg_rt.setGeometry(QtCore.QRect(0, -3, 231, 199))
        self.Bg_rt.setText("")
        self.Bg_rt.setPixmap(QtGui.QPixmap("bg_rt.png"))
        self.Bg_rt.setScaledContents(True)
        self.Bg_rt.setObjectName("Bg_rt")
        self.Bg_lft = QtWidgets.QLabel(self.centralwidget)
        self.Bg_lft.setGeometry(QtCore.QRect(502, 405, 301, 197))
        self.Bg_lft.setText("")
        self.Bg_lft.setPixmap(QtGui.QPixmap("bg_lft.png"))
        self.Bg_lft.setScaledContents(True)
        self.Bg_lft.setObjectName("Bg_lft")
        self.patch = QtWidgets.QLabel(self.centralwidget)
        self.patch.setGeometry(QtCore.QRect(510, 420, 141, 111))
        self.patch.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.978, y1:0.965909, x2:0.039, y2:0, stop:0 rgba(18, 12, 14, 255), stop:1 rgba(10, 38, 49, 255));")
        self.patch.setText("")
        self.patch.setScaledContents(True)
        self.patch.setObjectName("patch")
        self.User_Information = QtWidgets.QTextBrowser(self.centralwidget)
        self.User_Information.setGeometry(QtCore.QRect(510, 443, 141, 72))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.User_Information.setFont(font)
        self.User_Information.setStyleSheet("background:transparent;\n"
"color: rgb(0, 254, 253);\n"
"border:none;")
        self.User_Information.setObjectName("User_Information")
        self.User_Pic = QtWidgets.QLabel(self.centralwidget)
        self.User_Pic.setGeometry(QtCore.QRect(665, 440, 78, 79))
        self.User_Pic.setText("")
        self.User_Pic.setScaledContents(True)
        self.User_Pic.setObjectName("User_Pic")
        self.Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Date.setGeometry(QtCore.QRect(530, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Date.setFont(font)
        self.Date.setStyleSheet("background:transparent;\n"
"color: rgb(0, 254, 253);\n"
"border:none;")
        self.Date.setObjectName("Date")
        self.Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(640, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Time.setFont(font)
        self.Time.setStyleSheet("background:transparent;\n"
"color: rgb(0, 254, 253);\n"
"border:none;")
        self.Time.setObjectName("Time")
        self.Status = QtWidgets.QTextBrowser(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(610, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Status.setFont(font)
        self.Status.setStyleSheet("background:transparent;\n"
"color: rgb(0, 254, 253);\n"
"border:none;")
        self.Status.setObjectName("Status")
        self.StatusImg = QtWidgets.QLabel(self.centralwidget)
        self.StatusImg.setGeometry(QtCore.QRect(530, 147, 81, 61))
        self.StatusImg.setText("")
        self.StatusImg.setScaledContents(True)
        self.StatusImg.setObjectName("StatusImg")
        self.JarvisName = QtWidgets.QLabel(self.centralwidget)
        self.JarvisName.setGeometry(QtCore.QRect(486, 283, 231, 171))
        self.JarvisName.setText("")
        self.JarvisName.setPixmap(QtGui.QPixmap("JarvisName.png"))
        self.JarvisName.setScaledContents(True)
        self.JarvisName.setObjectName("JarvisName")
        self.Version = QtWidgets.QLabel(self.centralwidget)
        self.Version.setGeometry(QtCore.QRect(690, 362, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Version.setFont(font)
        self.Version.setStyleSheet("color:rgb(10, 38, 48)")
        self.Version.setObjectName("Version")
        self.LensButton = QtWidgets.QPushButton(self.centralwidget)
        self.LensButton.setGeometry(QtCore.QRect(600, 230, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LensButton.setFont(font)
        self.LensButton.setStyleSheet("background-color: rgb(2, 254, 253);\n"
"color: rgb(10, 38, 47);\n"
"border-radius:10px;")
        self.LensButton.setObjectName("LensButton")
        self.RecognitionMode = QtWidgets.QPushButton(self.centralwidget)
        self.RecognitionMode.setGeometry(QtCore.QRect(600, 270, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RecognitionMode.setFont(font)
        self.RecognitionMode.setStyleSheet("background-color: rgb(2, 254, 253);\n"
"color: rgb(10, 38, 47);\n"
"border-radius:10px;")
        self.RecognitionMode.setObjectName("RecognitionMode")
        self.ScanningMode = QtWidgets.QPushButton(self.centralwidget)
        self.ScanningMode.setGeometry(QtCore.QRect(600, 310, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ScanningMode.setFont(font)
        self.ScanningMode.setStyleSheet("background-color: rgb(2, 254, 253);\n"
"color: rgb(10, 38, 47);\n"
"border-radius:10px;")
        self.ScanningMode.setObjectName("ScanningMode")
        self.Patch_2 = QtWidgets.QLabel(self.centralwidget)
        self.Patch_2.setGeometry(QtCore.QRect(527, 217, 218, 137))
        self.Patch_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.852, x2:0, y2:0.097, stop:0 rgba(19, 40, 57, 255), stop:1 rgba(4, 65, 83, 255));")
        self.Patch_2.setText("")
        self.Patch_2.setObjectName("Patch_2")
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(150, 460, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Run.setFont(font)
        self.Run.setStyleSheet("color: rgb(10, 38, 47);\n"
"border-radius:10px;\n"
"background-color: rgb(70, 255, 156);")
        self.Run.setObjectName("Run")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(280, 460, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Exit.setFont(font)
        self.Exit.setStyleSheet("color: rgb(10, 38, 47);\n"
"border-radius:10px;\n"
"background-color: rgb(255, 96, 82);")
        self.Exit.setObjectName("Exit")
        self.Background.raise_()
        self.Patch_2.raise_()
        self.Bg_rt.raise_()
        self.Bg_lft.raise_()
        self.patch.raise_()
        self.User_Information.raise_()
        self.User_Pic.raise_()
        self.Date.raise_()
        self.Time.raise_()
        self.Status.raise_()
        self.StatusImg.raise_()
        self.JarvisName.raise_()
        self.Version.raise_()
        self.LensButton.raise_()
        self.RecognitionMode.raise_()
        self.ScanningMode.raise_()
        self.Run.raise_()
        self.Exit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.User_Information.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Date.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Time.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Status.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.Version.setText(_translate("MainWindow", "Ver: 2.0"))
        self.LensButton.setText(_translate("MainWindow", "Lens"))
        self.RecognitionMode.setText(_translate("MainWindow", "Recognise"))
        self.ScanningMode.setText(_translate("MainWindow", "Scan"))
        self.Run.setText(_translate("MainWindow", "RUN"))
        self.Exit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
